builds:
  - env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64]
archives:
  - name_template: lambdahttp
    format: zip
    files: [none*] # https://github.com/goreleaser/goreleaser/issues/602
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
