name: Release
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload zip
        uses: actions/upload-artifact@v1
        with:
          name: zip
          path: dist/lambdahttp.zip

  layers:
    runs-on: ubuntu-latest
    needs: [release]
    strategy:
      matrix:
        region: [ap-southeast-2, us-west-2, us-east-1]

    steps:
      - name: aws login
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ matrix.region }}

      - name: download zip
        uses: actions/download-artifact@v1
        with:
          name: zip

      - name: ls
        run: ls -lhR

      - name: publish
        uses: docker://awsteele/awscli
        with:
          args: >
            sh -c "
            aws lambda publish-layer-version
            --layer-name lambdahttp
            --compatible-runtimes provided
            --zip-file fileb://lambdahttp.zip
            --license-info MIT
            "
